board/urls.py
from django.urls import path, re_path
from board import views

app_name = 'board'

urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/ 한글도 인식 가능
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('add/', views.PostCreateView.as_view(), name='add'),

    path('change/', views.PostChangeLV.as_view(), name='change'),

    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),

    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import login, ResetPasswordView, ChangePasswordView, LoginDoneTV

from django.conf.urls import url
from mysite.views import HomeView
from users.forms import LoginForm
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('board/', include('board.urls')),
    path('user/', include('users.urls')),
    path('login/', login, name='login'),
    path('login/done/', LoginDoneTV.as_view(), name='login_done'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    url(r'^oauth/', include('social_django.urls', namespace='social')),
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

from account.models import User
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'board_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *arg, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*arg, **kwargs)

board/views.py
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from board.models import Post

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin
from django.conf import settings


#--- ListView
class PostLV(ListView):
    model = Post
    template_name = 'board/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


#--- DetailView
class PostDV(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'content']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'board/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'content']
    success_url = reverse_lazy('board:index')


class PostDeleteView(OwnerOnlyMixin, DetailView):
    model = Post
    success_url = reverse_lazy('board:index')

board/templates/board/post_all.html
{% extends "base.html" %}
{% block extra-style %}
<style type="text/css">
    a { text-decoration:none }
    .title {
    display: table-cell;
    vertical-align: middle;
}
</style>
{% endblock %}
{% block title %}post_all.html{% endblock %}
{% block content %}

    <h1>Board List</h1>&emsp;
    <br>

    {% for post in posts %}
        <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>&emsp;
        <div style="float:right"><img style="border-radius:5px; -moz-border-radius: 5px;
                    -khtml-border-radius:5px;
                    -webkit-border-radius:5px;" src="{{ post.owner.profile.avatar.url }} " width="25" height="25"/>{% firstof post.owner %}</div></h3>
        {{ post.modify_date|date:"N d, Y" }}
    {% endfor %}

    <br>
    <div style="float:left">
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>&emsp;&emsp;
    </div>
    <div class="title">
            <li class="nav-item mx-2 btn btn-primary">
                  <a class="text-white" href="{% url 'board:add' %}">Add</a>
            </li>
    </div>

{% endblock %}

board/templates/board/post_detail.html
{% extends "base.html" %}
{% block title %}post_detail.html{% endblock %}

{% block extra-style %}
<style>
.post-body{
    width: 80%;
    margin: auto;
    font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    font-size: 16px;
}
</style>
{% endblock extra-style %}

{% block content %}
<div class="post-body">

    <h2>{{ object.title }}</h2>
    <p>
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
            <i class="fas fa-arrow-circle-left"></i> {{ object.get_previous }}
        </a>
        {% endif %}

        {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
        {{ object.get_next }} <i class="fas fa-arrow-circle-right"></i>
        </a>
        {% endif %}
    </p>

    <div style="font-size:1.5em"><img style="border-radius:5px; -moz-border-radius: 5px;
                    -khtml-border-radius:5px;
                    -webkit-border-radius:5px;" src="{{ post.owner.profile.avatar.url }} " width="20" height="20"/>&emsp;{% firstof post.owner %}</div>
    <br>
    <p>{{ object.modify_dt|date:"j F Y" }}</p>
    <br>

    <div>
        {{ object.content|linebreaks }}
    </div>

    <br>

    <br>
</div>
{% endblock %}

board/templates/board/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block content %}

    <h1>Post Create/Update - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your post.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.slug|add_class:"form-control"|attr:"readonly" }}
            </div>
            <small class="form-text text-muted">{{ form.slug.help_text }}</small>
        </div>
        <div class="form-group row">
            {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.content|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>

{% endblock %}