board/urls.py
from django.urls import path, re_path
from board import views

app_name = 'board'

urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/ 한글도 인식 가능
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('add/', views.PostCreateView.as_view(), name='add'),

    path('change/', views.PostChangeLV.as_view(), name='change'),

    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),

    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import login, ResetPasswordView, ChangePasswordView, LoginDoneTV

from django.conf.urls import url
from mysite.views import HomeView
from users.forms import LoginForm
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('board/', include('board.urls')),
    path('user/', include('users.urls')),
    path('login/', login, name='login'),
    path('login/done/', LoginDoneTV.as_view(), name='login_done'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    url(r'^oauth/', include('social_django.urls', namespace='social')),
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Home{% endblock  %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block extra-style %} {% endblock %}

</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <span class="navbar-brand mx-1 mb-0 font-weight-bold font-italic" style="font-size:1.2em">PA1</span>
    
        <span class="nav-item mx-0 btn btn-primary"><a class="nav-link text-white" style="font-size:1.2em" href="{% url 'home' %}">Home</a></span>
        <span class="nav-item mx-0 btn btn-primary"><a class="nav-link text-white" style="font-size:1.2em" href="{% url 'board:index' %}">Board</a></span>
        <span class="nav-item dropdown mx-1 btn btn-primary" style="float:right">
            {% if user.is_active %}
            <a class="nav-link dropdown-toggle" style="font-size:1.2em; color: white;"  href="#" data-bs-toggle="dropdown">
                <img style="border-radius:5px; -moz-border-radius: 5px;
                    -khtml-border-radius:5px;
                    -webkit-border-radius:5px;" src="{{ user.profile.avatar.url }} " width="15" height="15"/>&ensp;{% firstof user.username %}&ensp;{{ user.points }}&ensp;</a>
            <div class="dropdown-menu">
                <span><a class="dropdown-item" href="{% url 'users-profile' %}">My Page</a></span>
                <span><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></span>
                <span><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></span>
            </div>
            {% else %}
            <a class="nav-link dropdown-toggle text-white" style="font-size:0.7em" href="#" data-bs-toggle="dropdown">
                <i class="fas fa-user"></i>&ensp;익명&ensp;</a>
            <div class="dropdown-menu">
                <span><a class="dropdown-item" href="{% url 'login' %}">Login</a></span>
                <span><a class="dropdown-item" href="{% url 'users-register' %}">Register</a></span>
            </div>
            {% endif %}
        </span>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/83c045e898.js" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
  .home-image{
    background-image: url("{% static 'img/lion.jpeg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
  }
  .title {
    color: #c80;
    font-weight: bold;
  }
  .powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
  }
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Home</h2>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Board function</h3>
            <p>You can write posts.</p>
        </div>
        <div class="col-sm-6">
            <h3>Profile function</h3>
            <p>You can make your own profile.</p>
        </div>
    </div>
    <hr style="margin: 10px 0;">
{% endblock content %}